### ISSUE TITLE
feature request: scale_continuous [low priority]

### ISSUE THREAD

**Issue by ptoche** [hadley/scales#107]
Hard work:

    library(ggplot2)
    library(scales)
    ggplot(data=mtcars, aes(x=mpg*10000, y=wt*10000)) +
        geom_point() +
        scale_y_continuous(labels = comma) +
        scale_x_continuous(labels = comma)

Lazy:

    ggplot(data=mtcars, aes(x=mpg*10000, y=wt*10000)) +
        geom_point() +
        scale_continuous(labels = comma)

**Comment by hadley** [comment]
This is a ggplot2 issue, and is partially implemented in ggplot2 2.3.0.
