### ISSUE TITLE
scales0.5.0 to R 3.2.1

### ISSUE THREAD

**Issue by alexandreliborio** [hadley/scales#110]
I've tried to install scales but I have the return
There is a binary version available but the source version is later:
       binary source needs_compilation
scales  0.4.0  0.5.0              TRUE

  Binaries will be installed
tentando a URL 'http://cran.cnr.berkeley.edu/bin/macosx/contrib/3.2/scales_0.4.0.tgz'
Content type 'application/x-gzip' length 276283 bytes (269 KB)
==================================================
downloaded 269 KB

The downloaded binary packages are in
	/var/folders/mg/yz7246613xb59g2s5wnz26g80000gn/T//RtmpxnJBgg/downloaded_packages

Even after update.packages, I can not download scales 0.5.0
Thank you

**Comment by alexandreliborio** [comment]
I am using OSX LIon 10.7.5

**Comment by dpseidel** [comment]
I'm closing this and #111 . As mentioned in #111,  https://community.rstudio.com/ is a more appropriate place for this kind of question.  If you're still having issues, please ask your question there. Good luck!
