### ISSUE TITLE
ERROR: compilation failed for package ‘scales’

### ISSUE THREAD

**Issue by alexandreliborio** [hadley/scales#111]
I had this when installing scales in osx r 3.2 ERROR: compilation failed for package ‘scales’.
How canIdonwload scales 0.4.1 or 0.5?
BEST

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer)
