### ISSUE TITLE
Feature request: discrete color scales that don't fail with too few colors

### ISSUE THREAD

**Issue by jnolis** [hadley/scales#112]
[moved this from [ggplot2](https://github.com/tidyverse/ggplot2/issues/2428)]

When you make a chart that uses many discrete colors, you never have to worry about the number of colors if you use the default colors.
```r
require(ggplot2)
ggplot(data.frame(x=letters[1:26],y=runif(26)),aes(x=x,y=y,fill=x))+geom_col()
```
![image](https://user-images.githubusercontent.com/3317138/35529808-075f5352-04e7-11e8-9c48-3015147ebd4c.png)

If you want to use your own colors (for instance, if you have company colors), it's easy to use a scale_manual to set the colors

```r
company_colors <-c("#E50000", "#008A8A", "#AF0076", "#E56800", "#1717A0", "#E5AC00", "#00B700")

ggplot(data.frame(x=letters[1:7],y=runif(7)),aes(x=x,y=y,fill=x)) +
geom_col() +
scale_fill_manual(values=company_colors)
```

![image](https://user-images.githubusercontent.com/3317138/35529873-30a62ed4-04e7-11e8-97b2-963531eca37c.png)

However, when you use this method you'll run into trouble if your number of needed colors is greater than the length of your color vector. This can be especially problematic because you generally want to just say "always use my company colors so I don't worry about it."

```r
ggplot(data.frame(x=letters[1:26],y=runif(26)),aes(x=x,y=y,fill=x)) +
geom_col() +
scale_fill_manual(values=company_colors)
Error: Insufficient values in manual scale. 26 needed but only 7 provided.
```

One solution to this is to create a function that makes a desired length vector of colors based on your existing ones:
```r
make_color_vector <- function(desired_length,base_colors){
  if(desired_length <= length(base_colors)){
    base_colors[1:n]
  } else {
    ramp_to_colors <- function(color,amount){
      if(amount > 1){
        current_color <- color
        return_colors <- c()
        for(a in 1:(amount)){
          return_colors <- c(return_colors,current_color)
          current_color <- grDevices::colorRampPalette(c(current_color,"#222222"))(4)[2]
        }
        return_colors
      } else {
        color
      }
    }
    iterations <- ceiling(desired_length/length(base_colors))
    as.vector(do.call(rbind,lapply(base_colors,function(x) ramp_to_colors(x,iterations))))[1:desired_length]
  }
}

ggplot(data.frame(x=letters[1:26],y=runif(26)),aes(x=x,y=y,fill=x)) +
geom_col() +
scale_fill_manual(values = make_color_vector(26, company_colors))
```

But the downside to this is you still need to keep track of how many colors you need.

__This seems like something that could be added to ggplot2 without breaking anything!__ One solution would be to let scale_fill_manual take a function which takes an integer as an input and returned the desired number of colors (rather than just a vector of colors). This feels similar to how some of the labels and breaks parameters work for scales. You could include the "make_color_vector" function within ggplot2 itself, or leave other people to make their own. Improving this functionality seems like it would help other packages downstream (like [ggthemr](https://github.com/cttobin/ggthemr), which sets default themes but breaks if your custom theme doesn't have enough colors).

I'm happy to help write the code to do this, but unfortunately I'm struggling to figure out where in the ggplot2 code base I would make these changes.

Thank you!

**Comment by hadley** [comment]
I think this is a really hard problem - your corporate style guide team will be unhappy if you modify their colours in this way, and if you just recycle the vector of colours you'll no longer have a unique mapping between value and colour.

**Comment by jnolis** [comment]
What if the user passed the function to scales, in a similar way to a labeling function? That function would take the number of colors the scale needs and would return the necessary colors. so like

```r
require(purrr)
require(stringr)
require(dplyr)
require(ggplot2)

# this randomly generates a color
rand_color <- function(){
  1:3 %>% 
    map_chr(~ str_pad(as.hexmode(floor(runif(1,0,256))),2,pad="0")) %>%
    paste0(collapse="") %>% 
    paste0("#",.)
}

# this is a function that, given a number, returns that number of colors
my_colors <- function(n) 1:n %>% map_chr(~ rand_color())

# here is a plot that will require 26 colors. In an ideal world I wouldn't need to know that number since my my_colors function will work with any number
data_frame(x = letters, y = 1:26) %>%
ggplot(aes(x=x, y=y, fill= x)) +
  geom_col() +
  scale_fill_manual(values=my_colors) # now I don't have to worry how many unique colors my data will need since the function will deal with it.
```

This would allow anyone to use whatever scaling they would like (so it's up to them to comply with their corporate scheme. I could imagine a different R package could include code to do multiple methods of color scaling and the user could select what they want (gradually become more white, more gray, loop, etc.).

**Comment by willgilks** [comment]
this worked for me. Repeat the colour palette enough times to cover all the groups, then shorten it, and add element names for ggplot:
```
## vector of random group names, longer than palette
groups=unlist(lapply(1:20,function (x) paste0(sample(letters,round(runif(1,2,5)),replace=T),collapse="")))

## palette base
pal=carto_pal(name="Safe")
ngrps=length(groups)
ncolours=length(pal)

## how many times the base palette needs to be repeated to cover all the group names
repeats_needed=ceiling(ngrps/ncolours)
all_colours=rep(pal,repeats_needed)

## restrict the length of the new colour vector to length of group names
length(all_colours)<-ngrps

## assign group names to colours
names(all_colours)<-groups
## use this in the call to ggplot()+scale_colour_manual(values=all_colours)
all_colours

```
