### ISSUE TITLE
Better error for 0-length colour

### ISSUE THREAD

**Issue by hadley** [hadley/scales#113]
```R
scales::hue_pal()(0)
#> Error in seq.default(h[1], h[2], length.out = n) : 
#>  'to' must be a finite number 
```

**Comment by dpseidel** [comment]
I'm debating how to be most informative to users encountering this error through `ggplot2`, without  inadvertently pointing the `scales` user in the wrong direction.  The `hue_pal` function is inherited by `ggplot2::scale_color_hue` and `ggplot2::scale_fill_hue` so errors need to be general to either `fill` or `color` arguments to `aes()`. 

Any advice would be most welcome,  I've reviewed the [style guide's points](http://style.tidyverse.org/error-messages.html) and looked over some examples of recently improved ggplot2 errors (ex. [1](https://github.com/tidyverse/ggplot2/commit/b0eea4b2e01ddcb394d7e63d7db48dcc1c093046), [2](https://github.com/tidyverse/ggplot2/commit/f61bfd620037b7e1c816129469b106443651a4dc), [3](https://github.com/tidyverse/ggplot2/commit/db62ebe981ad050e060210d17595506a7750a707)). 

Current best options: 
**1.  "`n` must be a positive integer. Please check the levels of your color argument."**

This error message does not make a ton of sense if encountered by directly calling `scales::hue_pal()(0)` but offers a useful hint for those users encountering it through ggplot2. The function actually does not require a positive integer (`n = .1`  will return 1 color code, `n = 3.1` will return 4) so perhaps this should be simplified to "`n` must be > 0"

**2.   "Can't return an empty color palette."  or "Can’t return a palette of length 0."**

This is plain enough to a user who has mistakenly called `scales::hue_pal()(0)` but less helpful to someone encountering this problem through `ggplot2`.


Given that this error is most likely to be run into through ggplot2  (and most enigmatic in that scenario), option 1 seems likely superior.

**Comment by hadley** [comment]
Hmmm, this is a little tricky because it's from an function generated by `hue_pal()`.  Maybe something like:

```R
scales::hue_pal()(0)
#> Error: Must request at least one colour from a hue palette, i.e.
#>   `n` must be positive integer, not 0.
```

I'm not sure it's worth a hint since it comes up pretty rarely.
