### ISSUE TITLE
tol argument in zero_range is too strict

### ISSUE THREAD

**Issue by richierocks** [hadley/scales#33]
The default argument to `zero_range`'s `tol` argument is currently `.Machine$double.eps * 100`, or about 2.2e-14.   This can cause ggplot to incorrectly warn about bars not being the same width.

See , e.g., 

http://stackoverflow.com/questions/14476961/why-do-i-get-position-dodge-requires-constant-width-even-though-widths-are-con

**Comment by hadley** [comment]
Not actually sure what it should be, but this seems like a common tolerance.
