### ISSUE TITLE
Return value too long for empty input to percent, dollar

### ISSUE THREAD

**Issue by richierocks** [hadley/scales#34]
The return value form each of the formatting functions should be the same length as the input.  This is usually true, except that the case with zero length inputs to the `percent` and `dollar` functions.

    empty_x <- numeric()
    percent(empty_x)      #returns "%"
    dollar(empty_x)       #returns "$"      

Suggested fixes:

    percent <- function (x) 
    {
      if(length(x) == 0) return(character())  #This line is new
      x <- round_any(x, precision(x)/100)
      str_c(comma(x * 100), "%")
    }

    dollar <- function (x) 
    {
      if(length(x) == 0) return(character())  #This line is new
      x <- round_any(x, 0.01)
      if (max(x, na.rm = TRUE) < largest_with_cents & !all(x == 
          floor(x), na.rm = TRUE)) {
          nsmall <- 2L
      }
      else {
          x <- round_any(x, 1)
          nsmall <- 0L
      }
      str_c("$", format(x, nsmall = nsmall, trim = TRUE, big.mark = ",", 
          scientific = FALSE, digits = 1L))
    }
    
Tests:

    test_that(
      "percent and dollar work with empty input",
      {
        x <- numeric()
        expected <- character()
        expect_identical(percent(x), expected)
        expect_identical(dollar(x), expected)      
      }
    )

**Comment by hadley** [comment]
Would you mind preparing a PR?

**Comment by BrianDiggs** [comment]
These tests are included in #35.
