### ISSUE TITLE
Missing log1p_implementation

### ISSUE THREAD

**Issue by andremrsantos** [hadley/scales#41]
Working over my data analysis, I face the need to present a value ranging from 0 to 700 using a log10 transformation. To avoid corrections like add +1 to the var, I decided to check the available transformations and found just what I was looking for in the log1p_trans().
Unfortunately, the function was not yet implement or at least I could not use it. To attend this issue may I propose a small correction using the following code:

    log1p_trans <- function(base) {
      trans_new("log1p", function(x) log(x+1,base), function(x) base^x - 1)
    }

This piece of code make everything work just fine here and I belive it should help others facing the same issue :+1:

**Comment by hadley** [comment]
It works for me as is. Do you have a minimal reprex?
