### ISSUE TITLE
annotate("segment", ...) fails after scale_x_datetime()

### ISSUE THREAD

**Issue by holstius** [hadley/scales#42]
Minimal example, adapted from code in help("scale_x_datetime"):

    start <- ISOdate(2001, 1, 1, tz = "")
    df <- data.frame(
      day30  = start + round(runif(100, max = 30 * 86400)),
      y = seq(1, 100)
    )

    library(ggplot2)
    qplot(day30, y, data = df)
    library(scales)
    last_plot() + scale_x_datetime(breaks = date_breaks("2 weeks")) 
    last_plot() + annotate("segment", x=start, xend=start + 1, y=50, yend=50)

Throws:

    Error in Ops.POSIXt((x - from[1]), diff(from)) : '/' not defined for "POSIXt" objects

**Comment by hadley** [comment]
This looks like a ggplot2 bug - could you please file the issue there? Here's a slightly better reprex:

```R
library(ggplot2)
start <- ISOdate(2001, 1, 1, tz = "")
df <- data.frame(
  x = start + 1:10,
  y = 1:10
)

# Works with segment + data
ggplot(df, aes(x, y)) + 
  geom_point() + 
  geom_segment(aes(xend = x + 1, yend = y), data = df[5, ])

# Fails with annotate
ggplot(df, aes(x, y)) + 
  geom_point() + 
  annotate("segment", x = start, xend = start + 1, y = 5, yend = 5)
```
