### ISSUE TITLE
Request: Additional formats

### ISSUE THREAD

**Issue by ggtim** [hadley/scales#47]
Dear Hadley,
Thanks a lot for your work on this package! 

While using it I encountered some problems with formats which might be solved by adding additional format templates.

The "comma_format" command offers a transformation from "1e+05" into "100,000". However, some countries do not use a comma as thousands separator. Instead, for example in Germany a point is used ("100.000"). Is it possible to either add a "point_format" (or similar) which transforms "1e+05" into "100.000"? If this would lead to too much work, could you integrate a format which simply gives the numbers without any transformation ("1e+05" -> "100000").

I have seen the "pull request" "Adding a function unit_format", which could also solve some of my format problems. Is this feature already live? I'm using version 0.2.4 and can't use the unit_format(.) command yet.

Again, thanks a lot for your work!

Best wishes.

PS: As I'm new to GitHub I hope this is the correct way to suggest new features for the package.

**Comment by mhermans** [comment]
A minor inconvenience, but als an European I keep finding myself adding a line defining an EU point-format to all my graph-code.

It would be cleaner if it was defined in the library. 

Are there objections (name clashes?) to a PR for formatter.r, defining `point` and `point_format`?
