### ISSUE TITLE
"bendy" linear lines on log2 scale

### ISSUE THREAD

**Issue by topepo** [hadley/scales#49]
Sorry of the inarticulate title...

Here is an example where the line that connect points show some bend to them:

    dat <- structure(list(C = c(0.25, 0.5, 1, 2, 4), 
                          RMSE = c(0.804624448979835, 0.711270401921118, 
                                   0.660698559131119, 0.63020003389642, 
                                   0.617379499367643)), 
                     .Names = c("C", "RMSE"), class = "data.frame", 
                     row.names = c(NA, 5L))
    
    ggplot(dat, aes(x = C, y = RMSE)) +  
      geom_point() + geom_line() + 
      coord_trans(x = "log2")

Using `scale_y_log10` doesn't show the same issue.

Thanks,

Max

**Comment by hadley** [comment]
Yes, that's because coordinate transforms don't in general preserve straight lines.
