### ISSUE TITLE
Improve col_factor's handling of color brewer palettes

### ISSUE THREAD

**Issue by jcheng5** [hadley/scales#62]
col_factor grabs the maximum number of colors available for a color brewer palette and then interpolates to produce n colors. Instead it should call brewer.pal with n.

**Comment by hadley** [comment]
Maybe it should use `brewer_pal()`?

**Comment by jcheng5** [comment]
Yeah, perhaps.

**Comment by hadley** [comment]
I don't have the time for this, but I'd review a PR.

**Comment by kent37** [comment]
Not sure why this is closed; `col_factor` with a qualitative color brewer palette is really broken. For example with `show_col(col_factor("Set1", levels = 1:4)(1:4))` only one of the resulting colors is actually in Set1. Unfortunately the breakage propagated to `leaflet::colorFactor` as well.

**Comment by bhaskarvk** [comment]
If brewer_pal() is used instead of interpolation, you lose the ability to generate more colors than the palette provides. This may break compatibility when someone was using col_factor to generate more colors than the palette provides.

**Comment by kent37** [comment]
Would it be possible to use interpolation only in the case where the number
of colors is more than the palette provides?

**Comment by jcheng5** [comment]
That's what I was thinking. And it may even be a good idea to warn if interpolation is required.

**Comment by jcheng5** [comment]
https://github.com/rstudio/leaflet/pull/364
