### ISSUE TITLE
Feature request: Support for tikz

### ISSUE THREAD

**Issue by kendonB** [hadley/scales#63]
This would, for example, include adding ``\`` before %, $ etc.

Hope this helps!

**Comment by hadley** [comment]
It doesn't really, as I don't use tikz. Could you expand on exactly what you want?

**Comment by kendonB** [comment]
\documentclass{article}    
    \begin{document}
    <<fig1, dev='tikz'>>=
    library(ggplot2)
    library(scales)
    # Works
    ggplot(iris) + aes(x = Sepal.Width, y = Sepal.Length) + geom_point() + 
      # Note the escape character for \ (to get it to work in R) and 
      # the escape character for % (to get the % symbol in LaTeX).
      xlab("Sepal.Width ($\\times$ 100\\%)")
    
    # Doesn't work
    ggplot(iris) + aes(x = Sepal.Width, y = Sepal.Length) + geom_point() + 
      # Note the escape character for \ (to get it to work in R) and 
      # the escape character for % (to get the % symbol in LaTeX).
      xlab("Sepal.Width ($\\times$ 100\\%)") + 
      scale_x_continuous(labels = percent)
    @
    \end{document}

I think it would just be a matter of defining a new ``logical`` option for the ``scale_*`` functions that ``gsub'ed`` ``"%"`` with ``"\\%"``, and ``"$"`` with ``"\\$"``.

**Comment by hadley** [comment]
I don't have the time for this, but I'd review a PR.
