### ISSUE TITLE
Feature Request: rank_trans

### ISSUE THREAD

**Issue by DarioS** [hadley/scales#64]
It would make it possible to easily use raw data as plot input, so that Spearman correlation could simply be calculated, because `cor` needs the raw data as input. For example,

    ggplot(plotData, aes(x, y)) + geom_point() + facet_wrap(~ groupID) +
           scale_x_continuous(trans = rank_trans()) + scale_y_continuous(trans = rank_trans()) +
           annotate("text", x = 0, y = 100, hjust = 0, label = paste("r =", round(cor(plotData[, 'x'], plotData[,'y'], method = "spearman"), 2))))

I think it should be in scales, since it seems like a not uncommon use-case.

**Comment by hadley** [comment]
It's not possible because you can't separate ranking into training and application steps.
