### ISSUE TITLE
prettyDate fails with very small ranges

### ISSUE THREAD

**Issue by hadley** [hadley/scales#65]
```R
df <- data.frame(
  x = Sys.time() + 1e-3 * 1:10, 
  y = cumsum(rnorm(10))
)
ggplot(df, aes(x, y)) + geom_point()
```

moved from https://github.com/hadley/ggplot2/issues/1395

**Comment by hadley** [comment]
This seems like a base R problem - I've emailed Paul Murrell.

**Comment by joshmyzie2** [comment]
Thanks, @hadley .  Do you know whether he created a bug report somewhere?  Just so that I can track its status.

**Comment by hadley** [comment]
It's fixed in R-devel.
