### ISSUE TITLE
"Dotted thousands" as labels

### ISSUE THREAD

**Issue by hauschke** [hadley/scales#66]
It would be really useful to have an option "dot" or "dottedThousands" for labels. In German, for example, a million is 1.000.000, not 1,000,000.

Discussion source: http://stackoverflow.com/questions/23263518/change-the-thousands-separator-in-a-ggplot#comment35601226_23263712

**Comment by hadley** [comment]
Unfortunately I don't have time to do this, but I'd be happy to review a PR.
