### ISSUE TITLE
extended_breaks fails if all NA

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/scales#73]
In reference to:
- https://github.com/hadley/ggplot2/issues/791
- https://github.com/hadley/ggplot2/issues/891

When ggplot has a facet with all NA values and tries to create a scale (using `scales::extended_breaks()`) it passes (-Inf, Inf) to `labeling::extended()`  which then fails to create a sane set of breaks and causes an error like:

`Error in seq.default(from = best$lmin, to = best$lmax, by = best$lstep) : 
  'from' must be of length 1`

To avoid the error/crash, check for non-finite min/max values in `scales::extended_breaks()` and return(0) instead of trying to create the breaks with `labeling::extended()`

i.e. change `extended_breaks()` to be:

``` r
extended_breaks <- function(n = 5, ...) {
  function(x) {
    if (!is.finite(min(x)) || !is.finite(max(x))) return(0)
    labeling::extended(min(x), max(x), n, only.loose = FALSE, ...)
  }
}
```

[patch.txt](https://github.com/hadley/scales/files/151882/patch.txt)

**Comment by karawoo** [comment]
Looks like this was fixed in 1cda5afe3f7875d2022af4789f8bee7aa82f6d80.
