### ISSUE TITLE
Scales pkg do not install in my 2009 32 bit Mac mini (El Capitan) 

### ISSUE THREAD

**Issue by ElvinMT** [hadley/scales#82]
I recently upgrade my 2009 Mac mini adding 2gb of ram and installing "El Capitan". For some reason when I try to install "ggplot2" the package Scales ask me for compile it, when I hit yes to continue the process a message appears saying that is unable to compile the dependency. When I check my installed packages the installed Scales version installed is the 0.4.0 and don't allow me to update it to the 0.4.1 version.  I try selecting another mirror and installing manually the newer version but it dosen't work. I also install gfortran 4.2.3 and tcltk 8.5.5x11 trying to solve the compiling problem.

The messages that appears are the following:
-"ERROR: compilation failed for package ‘scales’"
-"ERROR: lazy loading failed for package ‘ggplot2’"

I will appreciate any help.

Thanks!

**Comment by karawoo** [comment]
scales 0.4.1 should be on CRAN now so you don't need to build it yourself, but if you're still having problems let me know.
