### ISSUE TITLE
discard clashes with purrr::discard

### ISSUE THREAD

**Issue by holgerbrandl** [hadley/scales#84]
I could imagine that other users also run into the following situation
```
require(purrr)
require(scales)

keggPathways = c("mmu04660", "mmu03060", "mmu04110", "mmu04260", "mmu04723", "mmu05322", "mmu04114")

keggPathways %>% keep(~ .!="mmu04723")
keggPathways %>% discard(~ .=="mmu04723")
```
`keep` works as expected, but `discard` is overloaded by the `scales` packages and gives an incorrect empty result set.

Namespace conflicts are not really bugs for sure,  but it's at least a usability problem since both ggplot2/scales and purrr are likely to be used together.

**Comment by hadley** [comment]
I'd say our recommendation for this sort of problem is now to use https://www.tidyverse.org/articles/2018/06/conflicted/
